### ISSUE TITLE
v6.2 broke type inference for `pipe`? 

### ISSUE THREAD

**Issue by dotansimha** [0no-co/wonka#143]
Since v6.2 upgrade (from v6.1), we noticed that `pipe` is no longer inferred correctly when used, and it fall backs to `any`. 

reproduction: https://github.com/kamilkisiela/graphql-hive/pull/1348  

Seems like the `pipe` function is no longer having the TypeScript overrides it had before, and now IDE/TS compiler detect that as a function with no generics at all:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/3680083/218301539-5c40bd7d-98ff-4500-a29f-d40739ae2f17.png">

Even when specific explicitly, I get `Expected 0 type arguments, but got 1`.

**Comment by emilio-martinez** [comment]
I experienced this same issue. I believe this commit https://github.com/0no-co/wonka/commit/2cfe3e6a667181568cd7b84c785db2f1591d2d3b might be the cause cc @kitten

**Comment by kitten** [comment]
Should be fixed in `wonka@6.2.3` :v: Thanks for letting me know!
