### ISSUE TITLE
Narrowing overload for `filter`

### ISSUE THREAD

**Issue by isker** [0no-co/wonka#148]
In TS, `Array.filter` has an extra overload that supports narrowing the input type with a [type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates):
https://github.com/microsoft/TypeScript/blob/29c4b5e231e499cf506ea1c585d979b4d9d0459f/src/lib/es5.d.ts#L1234-L1245

Could wonka's `filter` do the same?  I wonder what `flowgen` would have to say about it, at least.

**Comment by kitten** [comment]
Yes! Quite coincidentally, I've just noticed yesterday that the double generic is actually missing 😅 I'll have to see whether it can be added in a patch

**Comment by isker** [comment]
Cheers!
