### ISSUE TITLE
Unable to access https://wonka.kitten.sh/ due to SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by fkling** [0no-co/wonka#173]
I'm getting the following error in Firefox 130.0 and (similar error) in Chrome 127.0.6533.88

```
Secure Connection Failed

An error occurred during a connection to wonka.kitten.sh. Cannot communicate securely with peer: no common encryption algorithm(s).

Error code: SSL_ERROR_NO_CYPHER_OVERLAP

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

I'm on Gentoo Linux if that matters.

**Comment by totorogendut** [comment]
This happens to me too on Edge Macos. I'm using wonka on my projects because it is such a great lighter alternative to rxjs and I'm hoping it still gets some bare minimum of maintenance to keep this project alive at least.

**Comment by kitten** [comment]
Should be resolved. Seems like my Cloudflare account had a stuck TLS certificate renewal due to some other shenanigans
