### ISSUE TITLE
Add makeReplaySubject source

### ISSUE THREAD

**Issue by EliaECoyote** [0no-co/wonka#75]
This should act as a subject, with the addition of emitting **immediately** old values to new subscribers, in FIFO order.

The api could look like:
```reason
let makeReplaySubject: (bufferSize: int) => subjectT('a) = ....;

// example:
let subject = makeReplaySubject(5);
```

I'm currently working on a PR, @kitten please tell me if you think this could be useful!

**Comment by kitten** [comment]
I was considering to add this already, since we use this in urql with some custom code!

Feel free to open a PR! I’d be happy to review this and get this feature in 👏🙌
